# data_characters.py

CHARACTERS = {
    "raya": {
        "name": "Raya Rivera",
        "nickname": "Rae",
        "traits": ["diligent", "considerate", "adventurous"],
        "stats": {
            "honest": 7,
            "charitable": 6,
            "funny": 4,
            "brave": 9,
            "romantic": 8,
            "curious": 6,
        },
        "prologue_relationships": {
            "emily": 6,
            "jace": 6,
            "harper": 5,
            "noah": 7,
            "mason": 5,
            "wyatt": 5,
            "avery": 6,
        },
        "story_relationships": {
            "emily": 10,
            "jace": 4,
            "harper": 6,
            "noah": 8,
            "mason": 5,
            "wyatt": 5,
            "avery": 6,
        },
    },

    "emily": {
        "name": "Emeline von Brixen",
        "nickname": "Emily",
        "traits": ["intelligent", "resourceful", "persuasive"],
        "stats": {
            "honest": 8,
            "charitable": 6,
            "funny": 4,
            "brave": 7,
            "romantic": 7,
            "curious": 9,
        },
        "prologue_relationships": {
            "raya": 6,
            "jace": 8,
            "harper": 7,
            "noah": 6,
            "mason": 5,
            "wyatt": 6,
            "avery": 4,
        },
        "story_relationships": {
            "raya": 10,
            "jace": 3,
            "harper": 6,
            "noah": 7,
            "mason": 5,
            "wyatt": 5,
            "avery": 5,
        },
    },

    "jace": {
        "name": "Jace Coleman",
        "nickname": "Jace",
        "traits": ["driven", "charismatic", "impulsive"],
        "stats": {
            "honest": 4,
            "charitable": 3,
            "funny": 6,
            "brave": 8,
            "romantic": 5,
            "curious": 5,
        },
        "prologue_relationships": {
            "raya": 6,
            "emily": 8,
            "harper": 7,
            "noah": 4,
            "mason": 8,
            "wyatt": 6,
            "avery": 3,
        },
        "story_relationships": {
            "raya": 4,
            "emily": 3,
            "harper": 6,
            "noah": 5,
            "mason": 7,
            "wyatt": 6,
            "avery": 4,
        },
    },

    "harper": {
        "name": "Harper Lin",
        "nickname": "Harper",
        "traits": ["confident", "opinionated", "outgoing"],
        "stats": {
            "honest": 5,
            "charitable": 4,
            "funny": 7,
            "brave": 6,
            "romantic": 6,
            "curious": 8,
        },
        "prologue_relationships": {
            "raya": 5,
            "emily": 7,
            "jace": 7,
            "noah": 5,
            "mason": 5,
            "wyatt": 6,
            "avery": 4,
        },
        "story_relationships": {
            "raya": 6,
            "emily": 6,
            "jace": 6,
            "noah": 5,
            "mason": 5,
            "wyatt": 5,
            "avery": 4,
        },
    },

    "noah": {
        "name": "Noah Sterling",
        "nickname": "Noah",
        "traits": ["inquisitive", "charming", "loyal"],
        "stats": {
            "honest": 8,
            "charitable": 9,
            "funny": 7,
            "brave": 5,
            "romantic": 5,
            "curious": 7,
        },
        "prologue_relationships": {
            "raya": 7,
            "emily": 6,
            "jace": 4,
            "harper": 5,
            "mason": 6,
            "wyatt": 4,
            "avery": 7,
        },
        "story_relationships": {
            "raya": 8,
            "emily": 7,
            "jace": 5,
            "harper": 5,
            "mason": 6,
            "wyatt": 5,
            "avery": 8,
        },
    },

    "mason": {
        "name": "Mason Donnelly",
        "nickname": "Mason",
        "traits": ["motivated", "ambitious", "active"],
        "stats": {
            "honest": 6,
            "charitable": 6,
            "funny": 8,
            "brave": 7,
            "romantic": 5,
            "curious": 6,
        },
        "prologue_relationships": {
            "raya": 5,
            "emily": 5,
            "jace": 8,
            "harper": 5,
            "noah": 6,
            "wyatt": 4,
            "avery": 3,
        },
        "story_relationships": {
            "raya": 5,
            "emily": 5,
            "jace": 7,
            "harper": 5,
            "noah": 6,
            "wyatt": 5,
            "avery": 4,
        },
    },

    "wyatt": {
        "name": "Wyatt Beckett",
        "nickname": "Wyatt",
        "traits": ["sarcastic", "guarded", "realistic"],
        "stats": {
            "honest": 7,
            "charitable": 3,
            "funny": 5,
            "brave": 7,
            "romantic": 4,
            "curious": 6,
        },
        "prologue_relationships": {
            "raya": 5,
            "emily": 6,
            "jace": 6,
            "harper": 6,
            "noah": 4,
            "mason": 4,
            "avery": 3,
        },
        "story_relationships": {
            "raya": 5,
            "emily": 5,
            "jace": 6,
            "harper": 5,
            "noah": 5,
            "mason": 5,
            "avery": 4,
        },
    },

    "avery": {
        "name": "Avery Moon",
        "nickname": "Avery",
        "traits": ["curious", "quiet", "superstitious"],
        "stats": {
            "honest": 7,
            "charitable": 7,
            "funny": 4,
            "brave": 5,
            "romantic": 4,
            "curious": 10,
        },
        "prologue_relationships": {
            "raya": 6,
            "emily": 4,
            "jace": 3,
            "harper": 4,
            "noah": 7,
            "mason": 3,
            "wyatt": 3,
        },
        "story_relationships": {
            "raya": 6,
            "emily": 5,
            "jace": 4,
            "harper": 4,
            "noah": 8,
            "mason": 4,
            "wyatt": 4,
        },
    },
}
